apiVersion: v1
kind: Pod
metadata:
  name: uw-madison-unet-3d-baseline
spec:
  restartPolicy: Never

  securityContext:
    runAsUser: 1020
    runAsGroup: 1020
    fsGroup: 1020

  volumes:
  - name: shmdir
    emptyDir:
      medium: Memory
  - name: pvc-volume
    persistentVolumeClaim:
       claimName: id202088518-pvc
  

  containers:
  - name: uw-madison
    image: quandapro/uw-madison:latest
    volumeMounts:
    - mountPath: /dev/shm
      name: shmdir
    - mountPath: /home/id202088518
      name: pvc-volume
    command:
      - "/bin/sh"
      - "-c"
    args:
      - cd /home/id202088518/Quan/uw-madison; python3 UWMGI_Unet_3D.py --batch 4 --description unet3d_ds --epoch 300 --ds 1 --unet 32x64x128x256x320 --trainsize 80x160x160x1
    securityContext:
      allowPrivilegeEscalation: false

    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
