apiVersion: v1
kind: Pod
metadata:
  name: uw-madison-logs-result
spec:
  restartPolicy: Never

  securityContext:
    runAsUser: 1020
    runAsGroup: 1020
    fsGroup: 1020

  volumes:
  - name: shmdir
    emptyDir:
      medium: Memory
  - name: pvc-volume
    persistentVolumeClaim:
       claimName: id202088518-pvc
  

  containers:
  - name: uw-madison
    image: quandapro/uw-madison:latest
    volumeMounts:
    - mountPath: /dev/shm
      name: shmdir
    - mountPath: /home/id202088518
      name: pvc-volume
    command:
      - "/bin/sh"
      - "-c"
    args:
      - cd /home/id202088518/Quan/uw-madison; python3 logger.py --folder ./model_checkpoint/resnet50
    securityContext:
      allowPrivilegeEscalation: false
  nodeName: gpu-3
